// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Rent-a-car helper;

{ITE} {DFMFileType} {addNewVehicle.dfm}
{ITE} {DFMFileType} {adminChange.dfm}
{ITE} {DFMFileType} {adminHome.dfm}
{ITE} {DFMFileType} {database.dfm}
{ITE} {DFMFileType} {home.dfm}
{ITE} {DFMFileType} {HTTP.dfm}
{ITE} {DFMFileType} {login.dfm}
{ITE} {DFMFileType} {register.dfm}
{ITE} {DFMFileType} {ticket.dfm}
{ITE} {DFMFileType} {vacation.dfm}
{ITE} {RCFileType} {Win32\Debug\Rent-a-car helper_DRC.rc}

{$R 'addNewVehicle.dfm' 'addVehicleWindow:TForm'}
{$R 'adminChange.dfm' 'changeAdmin:TForm'}
{$R 'adminHome.dfm' 'adminHomeWindow:TForm'}
{$R 'database.dfm' 'databaseWindow:TForm'}
{$R 'home.dfm' 'homeWindow:TForm'}
{$R 'HTTP.dfm' 'HTTPWindow:TForm'}
{$R 'login.dfm' 'loginWindow:TForm'}
{$R 'register.dfm' 'registerWindow:TForm'}
{$R 'ticket.dfm' 'ticketWindow:TForm'}
{$R 'vacation.dfm' 'vacationWindow:TForm'}
{$R 'Win32\Debug\Rent-a-car helper_DRC.res' 'Win32\Debug\Rent-a-car helper_DRC.rc'}

{$E HRV}

begin
end.
